### ISSUE TITLE
nuxi prepare doesn't create all `.d.ts` files

### ISSUE THREAD

**Issue by danielroe** [nuxt/framework#2401]
### Reproduction

reproducible in playground
```bash
❯ npx nuxi prepare && find .nuxt
Nuxt CLI v3.0.0-27324955.23397e6
.nuxt
.nuxt/nuxt.d.ts
.nuxt/tsconfig.json
```

### Describe the bug

Lots of files are missing, including files referenced within `nuxt.d.ts`. So type checking and IDE type support will fail.

**TODO**:
- [ ] handle generating types in Nuxt 3 - https://github.com/nuxt/framework/pull/2409
- [ ] handle generating types in Bridge - https://github.com/nuxt/framework/pull/2412
- [x] handle generating types in Nitro - https://github.com/nuxt/framework/pull/2413
