### ISSUE TITLE
Test utils support progress

### ISSUE THREAD

**Issue by pi0** [nuxt/framework#3198]
- [x] Initial version (#2952)
- [x] Silent verbose build logs (#3259)
- [x] Rewrite tests against new fixture (#3308)
- [x] Limited bridge testing
- [x] Mark playwright optional (resolving from user root)
- [x] `nuxt test` CLI (#3307)
- [x] Test nuxt in development mode (#3755)
- [x] Working browser testing
- [x] Documentation for setup and usage

Chore: 
- [x] Fix vitest issue with jiti esm stub (https://github.com/unjs/unbuild/issues/35)
- [ ] Merge with `test/` utils for build hashing and dedup (#582)

**Comment by yann-yinn** [comment]
Hi there. Will @nuxt/test-utils be able to handle **units testing / component testing** ? It is unclear to me when reading the issues. I can only see some exemples testing the whole page, but not a single component.

**Comment by pi0** [comment]
Let's go for the next steps!

Build hashing: #582

Module starter: https://github.com/nuxt/starter/issues/12

(`nuxi dev --test`: TODO)

**Comment by pi0** [comment]
> Will @nuxt/test-utils be able to handle units testing / component testing

@yann-yinn Honestly it is tricky to answer this today. Unit testing of SSR components needs a full running nuxt environment. Hopefully, we can achieve this with new nitropack possibilities and a custom entry point to introduce selective server rendering and enable unit testing of components within the tests.
